// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/1ec3d510e0c4d7c50e708ca7cb0765c7e06fa2ed/sqs-consumer/sqs-consumer.d.ts
declare module "sqs-consumer" {
  
  import { SQS } from "aws-sdk";
  
  module SQSConsumer {
    
    interface MessageHandler {
      (message: SQS.Message, done: Function): any;
    }
    
    interface ConsumerOpts {
      queueUrl: string;
      handleMessage: MessageHandler;
      region?: string;
      attributeNames?: string[];
      messageAttributeNames?: string[];
      batchSize?: number;
      visibilityTimeout?: number;
      waitTimeSeconds?: number;
      authenticationErrorTimeout?: number;
      sqs?: SQS;
    }
    
    interface Consumer extends NodeJS.EventEmitter {
      start (): void;
      stop (): void;
    }
    
    interface ConsumerFactory {
      create(opts: ConsumerOpts): Consumer;
    }
  }
  const Consumer: SQSConsumer.ConsumerFactory;
  export = Consumer;
  
}